import { Inter } from "next/font/google";
import "../../public/styles/theme.min.css";
import Header from "./Components/Header";
import BottomNav from "./Components/BottomNav";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
       <div className="overflow-hidden">
       {children}
       </div>
        <div className="lg:hidden fixed bottom-0 left-0 right-0 bg-white border-t py-4 z-10">
          <BottomNav />
        </div>
        <Footer />
      </body>
    </html>
  );
}
