import { Inter } from "next/font/google";
import "../../public/styles/theme.min.css";
import Header from "./Components/Header";
import BottomNav from "./Components/BottomNav";
import Footer from "./Components/Footer";
import ClientProvider from "./ClientProvider";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Create Next App",
//   description: "Generated by create next app",
//   author: "Your Name",
//   keywords: "Next.js, React, JavaScript, App, Web Development",
//   viewport: "width=device-width, initial-scale=1",
//   robots: "index, follow",
//   ogTitle: "Create Next App",
//   ogDescription: "Generated by create next app",
//   ogImage: "/path-to-image.jpg",
//   ogUrl: "https://www.yourwebsite.com",
//   ogSiteName: "Create Next App",
//   twitterCard: "summary_large_image",
//   twitterSite: "@yourhandle",
//   twitterCreator: "@yourhandle",
//   twitterImage: "/path-to-image.jpg",
//   favicon: "/favicon.ico", // Add the favicon reference here
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <Header />
          <div className="overflow-hidden">{children}</div>
          <div className="lg:hidden fixed bottom-0 left-0 right-0 bg-white border-t py-4 z-10">
            <BottomNav />
          </div>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
